### ISSUE TITLE
Expose nix-installed binaries in PATH

### ISSUE THREAD

**Issue by gdeest** [tweag/rules_nixpkgs#11]
Currently, there is no way to use nix-installed binaries in (e.g.) shell tests without directly referencing their full path in the script.

For example, we can make something like this to use Redis in a test:

`WORKSPACE` file:

```python
nixpkgs_package(
  name = "redis",
  repository = "@nixpkgs",
  nix_file_content = """
let nixpkgs = import <nixpkgs> {};
in nixpkgs.buildEnv {
  name = "numero-toolchain";
  paths = [ nixpkgs.redis ];
}
""",
  build_file_content = """
package(default_visibility = ["//visibility:public"])

filegroup(
  name = "bin",
  srcs = glob(["nix/bin/*"]),
)
""",
)
```

`BUILD` file:

```python
sh_test(
    name = "my-test",
    size = "small",
    srcs = ["my-test.sh"],
    data = ["@redis//:bin"]
)
```

`my-test.sh` file:

```bash
#!/usr/bin/env sh

./external/redis/nix/bin/redis-server
```

But we can"t invoke `redis-server` directly as it is not in `$PATH`. This makes the test depend on how Redis is installed, which is not satisfactory.

**Comment by johnynek** [comment]
I think the bazel way to go here is to use `location` expansion, not build up a `$PATH`:

https://docs.bazel.build/versions/master/be/general.html
```
Do use $(location) extensively, for outputs, tools and sources. Due to the segregation of output files for different configurations, genrules cannot rely on hard-coded and/or absolute paths.
```

**Comment by mboes** [comment]
This is not a `rules_nixpkgs`-specific issue. It depends entirely on the content of the `BUILD` file you provide. I'd recommend passing the location of the `redis-server` as an argument to your test script, as @johnynek suggests.
