### ISSUE TITLE
nixpkgs_local_repository dependency change doesn't invalidate nixpkgs_package

### ISSUE THREAD

**Issue by jcpetruzza** [tweag/rules_nixpkgs#113]
Given a `WORKSPACE` with something like this:

```bazel
nixpkgs_local_repository(
    name = "nixpkgs",
    nix_file = "//my/nixpkgs/default.nix",
    nix_file_deps = [ "//my/nixpkgs/something.nix"],
)

nixpkgs_package(
    name = "foo",
    attribute_path = "foo",
    repository = "@nixpkgs",
)
```

I'd expect that changes to `my/nixpkgs/something.nix` will force `@foo` to be rebuilt, but it seems that it doesn't and only changes to `my/nixpkgs/default.nix` will do. We had some reproducibility issues because of this, our workaround was to merge everything in one big file and avoid `nix_file_deps`.

From looking quickly through the code, the label `"@nixpkgs"` corresponds to `@nixpkgs//:nixpkgs` and this is symlinked to `my/nixpkgs/default.nix`, so iiuc, from the point of view of `bazel`, `@foo` only depends on that file, and not on `my/nixpkgs/something.nix`. I guess `@nixpkgs//:nixpkgs` could instead be defined to be a `filegroup()` containing the given `nix_file` and everything in `nix_file_deps`?

**Comment by aherrmann** [comment]
Thanks for reporting this!

The following should work correctly, i.e. adding `nix_file_deps` to the `nixpkgs_package` call:
```
nixpkgs_package(
    name = "foo",
    attribute_path = "foo",
    repository = "@nixpkgs",
    nix_file_deps = [ "//my/nixpkgs/something.nix"],
)
```

As you describe, it looks like right now `nix_file_deps` of `nixpkgs_local_repository` does not affect `nixpkgs_package`. I'm not sure that a `filegroup` will work here, since we're in the context of a `repository_rule`. However, what may work is to create additional symlinks in `nixpkgs_local_repository` for `nix_file_deps`.

**Comment by jcpetruzza** [comment]
Just to clarify, what I meant with the `filegroup()` is to define it in the `BUILD.bazel` file generated for the `@nixpkgs` repo, similar to what is done with, say, `:bin` and `:lib` in the external repositories created with `nixpkgs_package`. 

I'm not sure creating more symlinks in `nixpkgs_local_repository` would make a difference. It is already creating templates from them and they get updated on changes.

**Comment by aherrmann** [comment]
> I'm not sure creating more symlinks in `nixpkgs_local_repository` would make a difference. It is already creating templates from them and they get updated on changes.

Oh, [it is indeed](https://github.com/tweag/rules_nixpkgs/blob/115cd6d33c900089c399bad263e80889824ecddb/nixpkgs/nixpkgs.bzl#L43-L44). Sorry, I overlooked that.

> Just to clarify, what I meant with the `filegroup()` is to define it in the `BUILD.bazel` file generated for the `@nixpkgs` repo, similar to what is done with, say, `:bin` and `:lib` in the external repositories created with `nixpkgs_package`.

I see, and `nixpkgs_package` would then depend on that `filegroup`? That might work, do you want to give it a shot and open a PR if it works?

**Comment by mboes** [comment]
@jcpetruzza still working on this?

**Comment by jcpetruzza** [comment]
Sorry, I haven't had the time to work on this yet. If someone wants to look into it, by all means, go ahead! :slightly_smiling_face:
