### ISSUE TITLE
More explicit 'Platform is not supported' message?

### ISSUE THREAD

**Issue by smelc** [tweag/rules_nixpkgs#114]
While using rules_nixpkgs for [rules_haskell](https://github.com/tweag/rules_haskell/), I did the following:

```
> mkdir -p test/nested
> cd test
> git clone https://github.com/tweag/rules_haskell
> cd nested
> ./../rules_haskell/start --use-nix # Create rules_haskell standard template
> nix-shell --pure -p bazel
> bazel build //... # Try to build the template
Starting local Bazel server and connecting to it...
ERROR: An error occurred during the fetch of repository 'rules_haskell_sh_posix_nixpkgs':
   Platform is not supported (see 'fail_not_supported')
ERROR: /media/crypt1/repos/test/nested/BUILD.bazel:29:1: //:example depends on @rules_haskell_sh_posix_nixpkgs//:nixpkgs_sh_posix in repository @rules_haskell_sh_posix_nixpkgs which failed to fetch. no such package '@rules_haskell_sh_posix_nixpkgs//': Platform is not supported (see 'fail_not_supported')
ERROR: Analysis of target '//:example' failed; build aborted: no such package '@rules_haskell_sh_posix_nixpkgs//': Platform is not supported (see 'fail_not_supported')
INFO: Elapsed time: 15.039s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (17 packages loaded, 26 targets configured)
    Fetching @rules_haskell_ghc_nixpkgs_haskell_toolchain; Restarting. 12s
```

which is indeed to be expected, because I ran a `--pure` shell with only bazel (so no `nix*` on the `$PATH`).

I was however, puzzled by the `Platform is not supported` message; would it make sense to make explicit that `nix-build` was not found? (as it is what the implementation does: https://github.com/tweag/rules_nixpkgs/blob/master/nixpkgs/nixpkgs.bzl#L59-L60). I can write the patch, but wanted to make sure this is a desirable change beforehand.

**Comment by aherrmann** [comment]
That's a good point.

> would it make sense to make explicit that `nix-build` was not found?

Yes, I think that would be good. It could state that `nix-build` has to be in `PATH` and that `fail_not_supported` can be used if one doesn't want to use Nix.
