### ISSUE TITLE
Use Niv to fetch nixpkgs

### ISSUE THREAD

**Issue by nlewo** [tweag/rules_nixpkgs#127]
Instead of the custom `nixpkgs.json` and `nixpkgs.nix` files, we could use [Niv](https://github.com/nmattia/niv) to generate such files. This would allow use to update the nixpkgs revision/hash with a single command (`niv update nixpkgs`).

**Comment by aherrmann** [comment]
With flakes available now switching to flakes to provide `nixpkgs` may be a better option.

**Comment by tshaynik** [comment]
I would be happy to switch the project over to using flakes!

**Comment by aherrmann** [comment]
@tshaynik Nice, that would be a good change.
Beware that the are two layers to this. One is the Nix shell that provides Bazel, that should be reasonably straight forward, I expect. The other is [the `nixpkgs` that's imported into Bazel using `rules_nixpkgs`](https://github.com/tweag/rules_nixpkgs/blob/b942c09907154722ccb2c538115913317d956deb/WORKSPACE#L28). I think that's less straight forward, as `rules_nixpkgs` invokes `nix-build` and may need a compatibility layer access the `nixpkgs` attribute.
It may be better to split this task in two: One for the shell, and a separate one for importing `nixpkgs` from a flake.

**Comment by tshaynik** [comment]
Makes sense! I'll push a WIP pull request with the flake that provides the nix devShell today, and start looking into the more complex second part.
It will probably make sense to switch the invocation from the old `nix-build` to the flake-aware `nix build` as well.

**Comment by aherrmann** [comment]
> It will probably make sense to switch the invocation from the old `nix-build` to the flake-aware `nix build` as well.

Yes, perhaps, if so, be sure to check if this has compatibility breaking consequences.

**Comment by avdv** [comment]
Hi @tshaynik , 

sorry, I have been also working on this, but did not get around to pushing until now...

Could you please have a look at PR #265 ?!
