### ISSUE TITLE
More reproducibility: fetching nix as part of the rules

### ISSUE THREAD

**Issue by johnynek** [tweag/rules_nixpkgs#13]
Currently, these rules assume the existence of nix-build on the path. It would be nice to declare nix-build as either something bazel can build (which will probably be hard unless it has some nice bootstrapping already) or as binary files with hashes we can use on each platform.

With this, users don't need to install anything to use these rules, which is a bit nice.

**Comment by zimbatm** [comment]
It might be difficult. For a good nix experience the user needs root access to install the nix daemon and create the /nix/store. Nix can operate on a different prefix and without the daemon but it means loosing all the binary cache and sandboxing support.

**Comment by mboes** [comment]
I think #12 resolves this issue to satisfaction, and doing better than that will be hard for the reasons @zimbatm mentions.

**Comment by zimbatm** [comment]
One thing we might consider doing is create a docker image to host the build environment
