### ISSUE TITLE
[request] nixpkgs_python_configure support for 'quiet' attribute

### ISSUE THREAD

**Issue by thundergolfer** [tweag/rules_nixpkgs#130]
**Is your feature request related to a problem? Please describe.**

In `0.7.0` we got support for `quiet` attribute on `nixpkgs_package`. It's a nice feature, but when using `nixpkgs_python_configure` it's hidden from the user.

**Describe the solution you'd like**

Access to this attribute from `nixpkgs_python_configure`

**Additional context**

Would you accept a PR?

**Comment by aherrmann** [comment]
That's a good idea, it would also be a useful addition to other rules that call `nixpkgs_package`.

> Would you accept a PR?

Yes, a PR would be very welcome.

**Comment by mboes** [comment]
Fixed in #131.
