### ISSUE TITLE
Shorten repository name from `io_tweag_rules_nixpkgs` to `rules_nixpkgs`

### ISSUE THREAD

**Issue by Profpatsch** [tweag/rules_nixpkgs#144]
We switched `rules_haskell` from `@io_tweag_rules_haskell` to `@rules_haskell` in 0.10 (https://github.com/tweag/rules_haskell/blob/master/CHANGELOG.md#0100---2019-09-03), because apparently that’s the way to go according to upstream.

We should do the same for rules_nixpkgs.

cc @mboes

**Comment by mboes** [comment]
Upstream has since reverted their recommendation. See https://docs.bazel.build/versions/master/skylark/deploying.html#workspace. So let's stick to this name.
