### ISSUE TITLE
Question: Is it possible to use nixpkgs_package to obtain transitive closure of all dependencies

### ISSUE THREAD

**Issue by groodt** [tweag/rules_nixpkgs#149]
**Is your feature request related to a problem? Please describe.**
Is it possible to take an attribute from a nix repository and bundle the full transitive closure into a tarball?

**Describe the solution you'd like**
N/A
**Describe alternatives you've considered**
N/A

**Additional context**
Just wondering if it would be possible to use Nix for more than tools in the Bazel build. Can the files be actually shipped. For example, layering awscli into a container_image rule for example.

**Comment by aherrmann** [comment]
That's a good question. A good way to achieve this is to construct the bundle within Nix and then point `nixpkgs_package` at it.

For example, a Docker use-case is documented [here](https://rules-haskell.readthedocs.io/en/latest/haskell-use-cases.html#containerization-with-rules-docker). That uses `dockerTools` on the Nix side to generate a base image, imports it into Bazel using `nixpkgs_package`, and then forwards it to `rules_docker`. Does that cover the use-case you had in mind?

**Comment by groodt** [comment]
That does look interesting. Thanks! I'll take a closer look and hopefully it answers my question.

**Comment by aherrmann** [comment]
> That does look interesting. Thanks! I'll take a closer look and hopefully it answers my question.

@groodt Did that answer your question? I'll close for now. Feel free to reopen if it didn't.
