### ISSUE TITLE
Outdated documentation, nixpkgs_go_toolchain no longer exists?

### ISSUE THREAD

**Issue by stevana** [tweag/rules_nixpkgs#155]
The "Setup" section of the README contains the line:
```
load("@io_tweag_rules_nixpkgs//nixpkgs:toolchains/go.bzl", "nixpkgs_go_toolchain") # optional
```
If you add it do your WORKSPACE file then you get:
```
Error: file '@io_tweag_rules_nixpkgs//nixpkgs:toolchains/go.bzl' does not contain symbol 'nixpkgs_go_toolchain'
```
Also note that the `Example (optional nix support when go is a transitive dependency)` comment section of [`nixpkgs_go_configure`](https://github.com/tweag/rules_nixpkgs/blob/master/nixpkgs/toolchains/go.bzl#L42) also contains references to `nixpkgs_go_toolchain`.

**Comment by aherrmann** [comment]
@stevana Good catch, thank you for reporting this! Indeed, `nixpkgs_go_toolchain` does not exist. It should be `nixpkgs_go_configure` instead. #156 should fix the docs.
