### ISSUE TITLE
Environment variables set by nix-shell are leaking

### ISSUE THREAD

**Issue by jcpetruzza** [tweag/rules_nixpkgs#166]
**Describe the bug**
The toolchains provided by `rules_nixpkgs` are influenced by `TMP` and various other `NIX_*` environment variables, and the presence or absence of these variables on the host can then affect artifacts produced by repository rules, leading to invalidations and unncessary rebuilds.

Typically, these variables will only be set when running under nix-shell (directly or via direnv, etc). If one uses nix-shell locally for development, this then interacts badly with tmux, that only copies a few known environment variables from the caller. E.g. attempting to open ghci on a tmux pane with something like:
```
tmux split-pane -h bazel run //some/target:target@repl
```
will lead to the repository being rebuilt (and after using the repl, another full build will be needed for testing, etc.).

**To Reproduce**
We can verify that unsetting these environment variables forces the recompilation of dependencies when using rules_haskell.

```
$ git clone https://github.com/tweag/rules_haskell.git
$ cd rules_haskell/examples
$ echo "build --host_platform=@io_tweag_rules_nixpkgs//nixpkgs/platforms:host" > .bazelrc.local
$ bazel build @stackage//:conduit  # go get a coffee!
$ unset TMP $(env | grep '^NIX_' | cut -d= -f1)  # same effect as running under tmux
$ bazel build @stackage//:conduit  # go get another coffee!
$ exit; nix-shell --pure  # back to the normal env
$ bazel build @stackage//:conduit  # coffee time again...
```

**Expected behavior**
Changing those environment variables should have no noticeable effect, so the second and third calls, should have been no-ops.

**Environment**
 - OS name + version: NixOS 21.05
 - Version of the code: Same behaviour in 0.8.0 and latest commit

**Comment by aherrmann** [comment]
@jcpetruzza Thank you for raising this issue.

Could you determine which outputs differ between these configurations using execution logs (`--execution_log_json_file`) and how they differ? To that end you can look at the diff of the execution logs and compare files with different hashes.

I can reproduce a similar behavior by simply switching between building `rules_haskell/examples` inside a Nix shell, or outside a Nix shell, but still with the same Nix provided Bazel version as would be used inside the Nix shell. In that case one difference that causes cache misses is between the Python wrappers of the `cabal_wrapper` and `cc_wrapper-python`. Bazel autogenerates a wrapper script that hard-codes the path to the Python interpreter.
```
# Inside Nix shell
PYTHON_BINARY = '/nix/store/qyv5ffskmq8fv9yf5mb6fr5yracavid4-python3-3.8.7/bin/python3'
# Outside Nix shell
PYTHON_BINARY = '/usr/bin/python3'
```

**Comment by jcpetruzza** [comment]
@aherrmann  Thanks for suggesting `--execution_log_json_file`, I was trying to figure out how to do this. The problem seems to be in `external/local_config_cc/builtin_include_directory_paths`. This is what I get under nix-shell:
```
This file is generated by cc_configure and contains builtin include directories
that /nix/store/i9a3zzf2spmw67jppvkj2yavnbka62id-gcc-wrapper-10.2.0/bin/gcc reported. This file is a dependency of every compilation action and
changes to it will be reflected in the action cache key. When some of these
paths change, Bazel will make sure to rerun the action, even though none of
declared action inputs or the action commandline changes.

/nix/store/xjym8734qaqgz95y15gmqn5amngnj2l2-nix-2.3.10-dev/include
/nix/store/3h72x6pdanvjvvafsj9g0nzal7y8cmzr-boehm-gc-8.0.4-dev/include
/nix/store/qyv5ffskmq8fv9yf5mb6fr5yracavid4-python3-3.8.7/include
/nix/store/qpc15fcpmr93fpsv4s0rhwz5b6dbjsvl-openjdk-11.0.9+11/include
/nix/store/3dz52rv4ckfnkmjdcv6xl1qyw0gqxajd-file-5.39/include
/nix/store/11llddlvvvqcs3wpl1kifv9c71lzflmy-graphviz-2.42.2/include
/nix/store/yd4nslxqldgl2m2h53g3ig78far7vq4y-python3-3.7.9/include
/nix/store/ksld7jvgi3yg9w55mh7hlar0cymkil2m-libffi-3.3-dev/include
/nix/store/wxri3dc14yd1w997vjfvsnn6qml64l4r-gcc-10.2.0/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include
/nix/store/wxri3dc14yd1w997vjfvsnn6qml64l4r-gcc-10.2.0/include
/nix/store/wxri3dc14yd1w997vjfvsnn6qml64l4r-gcc-10.2.0/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/include-fixed
/nix/store/x1h3zxbr0bif0xr2l44x2pl5hnnc2n0j-glibc-2.32-35-dev/include
/nix/store/wxri3dc14yd1w997vjfvsnn6qml64l4r-gcc-10.2.0/include/c++/10.2.0
/nix/store/wxri3dc14yd1w997vjfvsnn6qml64l4r-gcc-10.2.0/include/c++/10.2.0/x86_64-unknown-linux-gnu
/nix/store/wxri3dc14yd1w997vjfvsnn6qml64l4r-gcc-10.2.0/include/c++/10.2.0/backward
```

While when built after sanitizing the environment with `unset TMP "${!NIX_@}"` this file contains only the gcc and glibc entries. The additional include directories are coming from `NIX_CFLAGS_COMPILE`:
```
$ echo $NIX_CFLAGS_COMPILE
-frandom-seed=s6lgdnnyx7 -isystem /nix/store/xjym8734qaqgz95y15gmqn5amngnj2l2-nix-2.3.10-dev/include -isystem /nix/store/3h72x6pdanvjvvafsj9g0nzal7y8cmzr-boehm-gc-8.0.4-dev/include -isystem /nix/store/qyv5ffskmq8fv9yf5mb6fr5yracavid4-python3-3.8.7/include -isystem /nix/store/qpc15fcpmr93fpsv4s0rhwz5b6dbjsvl-openjdk-11.0.9+11/include -isystem /nix/store/3dz52rv4ckfnkmjdcv6xl1qyw0gqxajd-file-5.39/include -isystem /nix/store/11llddlvvvqcs3wpl1kifv9c71lzflmy-graphviz-2.42.2/include -isystem /nix/store/yd4nslxqldgl2m2h53g3ig78far7vq4y-python3-3.7.9/include -isystem /nix/store/ksld7jvgi3yg9w55mh7hlar0cymkil2m-libffi-3.3-dev/include -isystem /nix/store/xjym8734qaqgz95y15gmqn5amngnj2l2-nix-2.3.10-dev/include -isystem /nix/store/3h72x6pdanvjvvafsj9g0nzal7y8cmzr-boehm-gc-8.0.4-dev/include -isystem /nix/store/qyv5ffskmq8fv9yf5mb6fr5yracavid4-python3-3.8.7/include -isystem /nix/store/qpc15fcpmr93fpsv4s0rhwz5b6dbjsvl-openjdk-11.0.9+11/include -isystem /nix/store/3dz52rv4ckfnkmjdcv6xl1qyw0gqxajd-file-5.39/include -isystem /nix/store/11llddlvvvqcs3wpl1kifv9c71lzflmy-graphviz-2.42.2/include -isystem /nix/store/yd4nslxqldgl2m2h53g3ig78far7vq4y-python3-3.7.9/include -isystem /nix/store/ksld7jvgi3yg9w55mh7hlar0cymkil2m-libffi-3.3-dev/include
```
and are references to packages in `shell.nix`.

Interestingly, it is not enough to unset all the `NIX_*` variables to trigger a rebuild: nix-shell places a copy of the environment in a `$TMP/env-vars` file, which can also be picked up, so one needs to unset `TMP` as well.

**Comment by aherrmann** [comment]
@jcpetruzza Thanks for the quick reply. The good news is that `rules_nixpkgs` provides a mechanism to avoid this specific issue: [`nixpkgs_cc_configure`](https://github.com/tweag/rules_nixpkgs/#nixpkgs_cc_configure). That repository rule generates the toolchain configuration, including `builtin_include_directory_paths`, inside a Nix derivation. Meaning, this step is sandboxed by Nix and should be unaffected by environment variables.

Note, that this hermetic version of `nixpkgs_cc_configure` only exists since https://github.com/tweag/rules_nixpkgs/pull/128, which is included in v0.8.0 of rules_nixpkgs. Older versions of `nixpkgs_cc_configure` build on top of Bazel's builtin cc toolchain detection and are still susceptible to environment variables such as `NIX_CFLAGS_COMPILE`. Bazel's builtin default cc toolchain detection is entirely based on looking up the compiler and its configuration in the environment.

If you use the default `name = "local_config_cc"`, then this Nix provided toolchain will fully replace Bazel's builtin default cc toolchain. Otherwise, you will need to enable the toolchain using `--crosstool_top` or by enabling cc toolchain resolution via `--incompatible_enable_cc_toolchain_resolution`.

**Comment by jcpetruzza** [comment]
Oh, I had forgotten to set `--incompatible_enable_cc_toolchain_resolution` in `.bazelrc`!  I had started with a `nixpkgs_cc_configure` with the default name and once I noticed it wouldn't work when nix was not installed, I renamed the toolchain  and failed to enable toolchain resolution. Anyway, thanks @aherrmann!

Out of curiosity, are there known issues with `--incompatible_enable_cc_toolchain` atm? There is a comment in rules_nixpkgs' .bazelrc saying it can't be recommended yet, and I see it's not enabled by default in rules_haskell's either.

**Comment by aherrmann** [comment]
> Out of curiosity, are there known issues with `--incompatible_enable_cc_toolchain` atm? There is a comment in rules_nixpkgs' .bazelrc saying it can't be recommended yet, and I see it's not enabled by default in rules_haskell's either.

Good question, this was discussed in https://github.com/tweag/rules_nixpkgs/pull/128#discussion_r550588251 at the time. An observation was that despite `--incompatible_enable_cc_toolchain` being enabled and the Nix provided toolchain being selected there were still some references to `local_config_cc`. The corresponding Bazel issue https://github.com/bazelbuild/bazel/issues/12712 is still open.
