### ISSUE TITLE
Can I use it in genrule?

### ISSUE THREAD

**Issue by JohnAZoidberg** [tweag/rules_nixpkgs#173]
**Is your feature request related to a problem? Please describe.**
I'm trying to slowly integrate Bazel into an existing (huge) project. For that purpose I'm staring with wrapping the existing make-based build system with Bazel and would like to use Nix to get my dependencies.

Since I'm starting out with only one rule that will be generating just one binary by calling a Python build system, that calls make, I think I have to use `genrule` (right?). I'm new to bazel, so I might be going about things the wrong way.

I set up the `WORKSPACE` as described in the README and I can add `make` to the `tools` attribute of `genrule` and can use it (only explicitly, not via `$PATH`).
But then, of course, it cannot find the compiler.

```bazel
# WORKSPACE
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "rules_cc",
    sha256 = "4dccbfd22c0def164c8f47458bd50e0c7148f3d92002cdb459c2a96a68498241",
    urls = [
        "https://github.com/bazelbuild/rules_cc/releases/download/0.0.1/rules_cc-0.0.1.tar.gz",
    ]
)

http_archive(
    name = "io_tweag_rules_nixpkgs",
    strip_prefix = "rules_nixpkgs-0.8.0",
    urls = ["https://github.com/tweag/rules_nixpkgs/archive/v0.8.0.tar.gz"],
    sha256 = "7aee35c95251c1751e765f7da09c3bb096d41e6d6dca3c72544781a5573be4aa",
)

load("@io_tweag_rules_nixpkgs//nixpkgs:repositories.bzl", "rules_nixpkgs_dependencies")
rules_nixpkgs_dependencies()

load("@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl", "nixpkgs_git_repository", "nixpkgs_package", "nixpkgs_cc_configure")

nixpkgs_git_repository(
    name = "nixpkgs",
    revision = "21.11", # Any tag or commit hash
    sha256 = "c77bb41cf5dd82f4718fa789d49363f512bb6fa6bc25f8d60902fe2d698ed7cc",
)

nixpkgs_cc_configure(
        repository = "@nixpkgs//:default.nix",
        fail_not_supported = False,
)
nixpkgs_package(
    name = "gnumake",
    #attribute_path = "libuuid.dev",
    repositories = { "nixpkgs": "@nixpkgs//:default.nix" }
)
nixpkgs_package(
    name = "libuuid",
    attribute_path = "libuuid.dev",
    repositories = { "nixpkgs": "@nixpkgs//:default.nix" }
)

load("@rules_cc//cc:repositories.bzl", "rules_cc_dependencies", "rules_cc_toolchains")
rules_cc_dependencies()
rules_cc_toolchains()
```

```bazel
# BUILD.bazel
genrule(
    name = "firmware",
    srcs = glob(["**"]),
    outs = [
        "OVMF_CODE.fd",
        "OVMF_VARS.fd",
    ],
    tools = [ "@gnumake//:bin" ],
    cmd = """
        # The edk2 build does not like Bazel's default genrule environment.
        set +u
        . edksetup.sh
        $(execpath @gnumake//:bin) -C BaseTools/Source/C
        build -t GCC5 -a X64 -b RELEASE -p $$PWD/OvmfPkg/OvmfPkgX64.dsc
        cp Build/OvmfX64/RELEASE_GCC5/FV/{OVMF_CODE.fd,OVMF_VARS.fd} $(RULEDIR)
    """,
    visibility = ["//visibility:public"],
)
```

**Describe the solution you'd like**
Use rules_nixpkgs in genrule, not in cc_binary because I'm wrapping an existing build system.

**Describe alternatives you've considered**
Maybe it's possible to use cc_binary or other rules to achieve what I want?

Previously I tried to use the default `genrule` environment with an empty `WORKSPACE` file and use `nix-shell` to get my dependencies but I wasn't able to make it find the header from `libuuid`

**Additional context**
```
> bazel build //:firmware
INFO: Analyzed target //:firmware (1 packages loaded, 12862 targets configured).
INFO: Found 1 target...
ERROR: /home/zoid/cloudhome/hpe/taiwan/flat-edk2/BUILD.bazel:1:8: Executing genrule //:firmware failed (Exit 2): bash failed: error executing command /nix/store/pprdrvp8bjcd5cllzb5qj0zcgb10yxfa-bash/bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox bash failed: error executing command /nix/store/pprdrvp8bjcd5cllzb5qj0zcgb10yxfa-bash/bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
make[1]: gcc: No such file or directory
make[1]: *** [../Makefiles/footer.makefile:21: BasePeCoff.o] Error 127
make: *** [GNUmakefile:76: Common] Error 2
```

**Comment by aherrmann** [comment]
`nixpkgs_cc_configure` defines and registers a CC toolchain, which Bazel then may select based on the [configured platform](https://docs.bazel.build/versions/main/platforms-intro.html). You'll need to set `build --host_platform=@io_tweag_rules_nixpkgs//nixpkgs/platforms:host` in `.bazelrc` or pass the flag on the command line to make the Nix provided toolchain available.

Some toolchains, including the CC one, provide [Make variables](https://docs.bazel.build/versions/main/be/make-variables.html#custom_variables) like `$(CC)` to reference some of the tools or paths provided by that toolchain. For that to work you need to add `toolchains = ["@bazel_tools//tools/cpp:current_cc_toolchain"]` to the genrule as described in the linked documentation. You can then add `$(CC)` to the genrule's command and it will be expanded to the path to the compiler.

**Comment by JohnAZoidberg** [comment]
> Some toolchains, including the CC one, provide [Make variables](https://docs.bazel.build/versions/main/be/make-variables.html#custom_variables) like `$(CC)` to reference some of the tools or paths provided by that toolchain. For that to work you need to add `toolchains = ["@bazel_tools//tools/cpp:current_cc_toolchain"]` to the genrule as described in the linked documentation. You can then add `$(CC)` to the genrule's command and it will be expanded to the path to the compiler.

Oh that's very useful, thanks! That gets me a bit further.

How can I add C library dependencies?
And how can I add a program to the PATH? My build requires some other programs, like Python to be available.
