### ISSUE TITLE
Latest rules_rust incompatible with nixpkgs_rust_configure

### ISSUE THREAD

**Issue by igrekun** [tweag/rules_nixpkgs#205]
**Describe the bug**
Changing rules_rust revision breaks compatibility

`external/nix_rust/rust_nix_impl/bin/cargo failed: missing input file 'external/nix_rust/cargo', owner: '@nix_rust//:cargo'`

**To Reproduce**
Use the commented revision and hash (latest as of now)
```
revision = "dc66c1612b7a3e96531eff22136570124c8eec81"
#revision = "635da93206c2761d9db58ed82e194d2af053faf6"
http_archive(
    name = "rules_rust",
    sha256 = "9dadbcd1136f7d4f3f2e7c0790531be0fdcccc535dec42a4c5a6f2df7380e3e3",
    #sha256 = "aeaa5b98891c646c5292d36f1ce84682f353395aacddafd6c3d6e0db3026eb85",
    strip_prefix = "rules_rust-{}".format(revision),
    urls = [
        # `main` branch as of 2021-12-01
        "https://github.com/bazelbuild/rules_rust/archive/{}.tar.gz".format(revision),
    ],
)
```

**Expected behavior**
bazel build //... works

**Environment**
 - OS name + version:
 - Version of the code:

**Additional context**

**Comment by fricklerhandwerk** [comment]
@igrekun Please check if #204 solves your issue.

**Comment by igrekun** [comment]
Yeah, works great on latest commit.
