### ISSUE TITLE
Attribute `path` for `nixpkgs_package` doesn't accept a relative path

### ISSUE THREAD

**Issue by YPares** [tweag/rules_nixpkgs#21]
I have to specify an absolute path or else I'm getting:

`warning: Nix search path entry 'nixpkgs.nix' does not exist, ignoring`

Also this shouldn't be a warning, but a full-fledged error.

**Comment by regnat** [comment]
You can't refer to them using the `path` attribute, but you can refer to them by their label with the `repository` (or `repositories` once #29 is merged) attribute.

> Also this shouldn't be a warning, but a full-fledged error.

Unfortunately, this warning is emitted by nix and we don't have the hand on it (though I agree with you on the principle).

**Comment by Profpatsch** [comment]
It’s directly spliced into `NIX_PATH`, which accepts relative paths but then resolves them *relative to the current working directory*.

In practice you should use bazel targets instead, which will be resolved to absolute paths. Something like `path = ":nixpkgs.nix"`.
