### ISSUE TITLE
Provide toolchain for rules_go and rules_node

### ISSUE THREAD

**Issue by kalbasit** [tweag/rules_nixpkgs#22]
Hello,

Can this be used to provide binaries required by rules_go and rules_nodejs?

Go toolchain can be configured as explained [here](https://github.com/bazelbuild/rules_go/blob/master/go/toolchains.rst).

NodeJS is a bit more complex, so far I got it to work by doing the following:

```
node_repositories(
    package_json = [
        "//rules_nodejs:package.json",
    ],

    node_path = "/nix/store/q05xbja14rsgqzknmmlkajnzacjnp4hl-nodejs-8.11.3",
    yarn_path = "/nix/store/fc9n30kjp7q04s520w4n34c3rbhsqdnl-yarn-1.8.0/libexec/yarn",
)
```

which means that I somehow need to get the location of `@nodejs//:bin/node`. Is this possible?

See full example [here](https://github.com/kalbasit/nixpkgs/blob/test-bazel/pkgs/test/bazel/WORKSPACE)

**Comment by mboes** [comment]
Looks like this was [resolved upstream](https://github.com/NixOS/nixpkgs/issues/43955).

**Comment by kalbasit** [comment]
@mboes actually rules_go added support for Go coming from NIx or other sources, see https://github.com/bazelbuild/rules_go/issues/1611
