### ISSUE TITLE
Problem when running with a non-release Bazel version

### ISSUE THREAD

**Issue by mai93** [tweag/rules_nixpkgs#229]
After [rules_haskell](https://github.com/tweag/rules_haskell) updated their `rules_nixpkgs` version in commit https://github.com/tweag/rules_haskell/commit/bfcec89006d4e54b523847ccddccfba36c3a12fc, their tests with Bazel@Head started to fail ([example](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2480#ccc56079-febc-47c3-bbfd-e1d05c868520)). I think the reason is that [this check](https://github.com/tweag/rules_nixpkgs/blob/master/toolchains/python/python.bzl#L59) that was added in the new version and it does not take into account using non-release Bazel binaries.

**Comment by avdv** [comment]
Thank you for the heads-up!

**Comment by AleksanderGondek** [comment]
I am bit late to the party: [PR](https://github.com/tweag/rules_nixpkgs/pull/231)
I have allowed myself to compete with @avdv, cause I am also fixing other usages of "versions.at_least" from skylib :)

**Comment by meteorcloudy** [comment]
This is still failing with Bazel@HEAD + rules_haskell @ b8ac6c18d26c0011a2464200762e45302a70bbf6, can you please also send a PR to update the rules_nixpkgs version in rules_haskell?

**Comment by avdv** [comment]
> This is still failing with Bazel@HEAD + rules_haskell @ b8ac6c18d26c0011a2464200762e45302a70bbf6, can you please also send a PR to update the rules_nixpkgs version in rules_haskell?

PR is pending since it currently fails on CI:  tweag/rules_haskell#1750
