### ISSUE TITLE
--config-ci | build-buddy configuration seems to not be working correctly in the CI

### ISSUE THREAD

**Issue by AleksanderGondek** [tweag/rules_nixpkgs#238]
Current CI configuration, in regards to Build-buddy setup, seems to be broken.

**Extended description**
I can see two issues with current setup:

1. The `.bazelrc.local` file which is supposed to equip Bazel with BBuddy authentication key, is created solely for the "." WORKSPACE. "core" or any of the toolchain workspaces will not be able to read it and thus will not run in the "--config=ci", nor will they be able to use the auth key. Consequently, issues observed with Bbuddy configuration are observed only in "." WORKSPACE checks.
2. The buildbuddy authentication key, seems to be either expired or read-only (at least, that is my read on the situation).

**To Reproduce**
Create a PR that results in modification of "." WORKSPACE.

See: 
- https://github.com/tweag/rules_nixpkgs/pull/236 (notice diff between first and second commit)
- https://github.com/tweag/rules_nixpkgs/runs/6778395524?check_suite_focus=true (take a look at the ubuntu checks, the macos is failing for other, proper reasons)

**Expected behavior**
The CI check should:
1. Fail with clear message as to why the failure occurred (at the moment it is quite cryptic)
2. The `.bazelrc.local` file should be used in all or none workspaces
3. The bbuddy authetication key should work
4. If Bazel tests pass, the CI should pass :) 

**Environment**
 - NixOS 22.05
 - Ubuntu 2{0,2}.04

**Additional context**
- I am only sure of the impact of using `.bazelrc.local` in the bazel testing
- Thanks @@patryk-kozak for helping me :)

**Comment by benradf** [comment]
From the comments in #236 I see this was superseded by #243. As that issue has now been closed, I'm closing this one too. Let me know if you disagree.
