### ISSUE TITLE
Video in the README is no longer available

### ISSUE THREAD

**Issue by bryanhonof** [tweag/rules_nixpkgs#241]
I just noticed that the video pointed to in the [README](https://github.com/tweag/rules_nixpkgs/blob/master/README.md), [Nix + Bazel (lightning talk)](https://www.youtube.com/watch?v=hDdDUrty1Gw), isn't available anymore. Did it move somewhere else, or did it just disappear?

**Comment by aherrmann** [comment]
Good catch! I don't know what happened to that link. It looks like the talk is still available [here](https://www.youtube.com/watch?v=7-K_RmDasEg&t=2030s). Could you update the README?
