### ISSUE TITLE
Is nixpkgs_git_repository@revision required?

### ISSUE THREAD

**Issue by philderbeast** [tweag/rules_nixpkgs#26]
For `nixpkgs_git_repository`, the attribute **revision** is marked as `String; optional` in the readme but it looks to be required.

In the WORKSPACE file, for `nixpkgs_git_repository` set only name, the only required attribute;

```
nixpkgs_git_repository(
    name = "nixpkgs",
)
```

With that, the build cannot download nixpkgs;

```
> bazel build //...
...
no such package '@ghc//':
no such package '@nixpkgs//':
java.io.IOException: Error downloading [https://github.com/NixOS/nixpkgs/archive/.tar.gz]
```

Here's where the URL is constructed;

https://github.com/tweag/rules_nixpkgs/blob/fb89dc9c5f3441fb065a07230bd6c7329c797b80/nixpkgs/nixpkgs.bzl#L8

The relevant section of the readme;

https://github.com/tweag/rules_nixpkgs/blame/master/README.md#L70-L75

**Comment by Fuuzetsu** [comment]
I think it's a bug. It used to not be required but I believe it is these days. The optional should prpbably go away.
