### ISSUE TITLE
Split the docs generation into a separate component

### ISSUE THREAD

**Issue by avdv** [tweag/rules_nixpkgs#264]
**Is your feature request related to a problem? Please describe.**

Currently, every component depends on `java`, `posix` and the `cc` toolchain (even the core). This is because of the stardoc dependency which consists of a `java_binary` and is used to generate documentation from starlark.

Ideally, the `core` should not depend on any other toolchain at all. Other toolchains should also not depend on any other toolchain that is indeed not used by it.

**Describe the solution you'd like**

Make the docs generation a component of its own.

**Describe alternatives you've considered**

**Comment by avdv** [comment]
@z8v I think we should be able to get rid of the reference to the docs module in core now. It is still referenced but not actually used there.

Also, the idea was to get rid of the dependency on the docs module in all toolchains too.

**Comment by z8v** [comment]
@avdv Although the docs are not used explicitly used, the core and `toolchains` reference dependencies introduced by the `docs` module. Should we introduce those dependencies directly on `core` and the `toolchains`? This means duplicating (minus the `stardoc` dependency) the `docs_dependencies_X.bzl` files on `core`.

The `toolchains` directly call `generate_documentation` on the `docs` directory. Should we remove this?

I've opened https://github.com/tweag/rules_nixpkgs/pull/304 to address the first part. Let me know if this is what you had in mind.
