### ISSUE TITLE
nixpkgs_rust_configure() assumes .so file extension, breaks MacOS

### ISSUE THREAD

**Issue by cloneable** [tweag/rules_nixpkgs#281]
**Describe the bug**

I wanted to use `nixpkgs_rust_configure()` to set `default_edition` to `2021`, but then had trouble building openssl-macros crate:

```
ERROR: /private/var/tmp/_bazel/98a8c1de72415124e1440463e5f890b1/external/crate_index__openssl-macros-0.1.0/BUILD.bazel:34:16: output 'external/crate_index__openssl-macros-0.1.0/libopenssl_macros-924812929.so' was not created
ERROR: /private/var/tmp/_bazel/98a8c1de72415124e1440463e5f890b1/external/crate_index__openssl-macros-0.1.0/BUILD.bazel:34:16: Compiling Rust proc-macro openssl_macros v0.1.0 (1 files) failed: not all outputs were created or valid
Target @crate_index__openssl-macros-0.1.0//:openssl_macros failed to build
```

Took me a while to notice the `.so` extension. I tracked this down to this unconditional setting:
https://github.com/tweag/rules_nixpkgs/blob/439cd5b6c79791105e9d475285293c6e207fc945/toolchains/rust/rust.bzl#L166

**To Reproduce**

On MacOS, call `nixpkgs_rust_configure()` in `WORKSPACE` file.

**Environment**
 - OS name + version: MacOS
 - Version of the code: 0.9.0

**Comment by cloneable** [comment]
Yes, sounds good. I need this anyway. 

How about this?
```nix
let
    dylib-ext = if pkgs.stdenv.targetPlatform.isDarwin then ".dylib" else ".so";
```

And use `${dylib-ext}` in the bazel code. To be consistent I think the static lib and executable extensions should be set like this, too, right?

**Comment by aherrmann** [comment]
@cloneable Thank you!
Yes, that sounds right to me.
> To be consistent I think the static lib and executable extensions should be set like this, too, right?

Agreed.

**Comment by benradf** [comment]
Fixed in [PR 305](https://github.com/tweag/rules_nixpkgs/pull/305).
