### ISSUE TITLE
`nixpkgs_cc_configure` should allow `attribute_path` without having a nix file

### ISSUE THREAD

**Issue by evertedsphere** [tweag/rules_nixpkgs#328]
**Is your feature request related to a problem? Please describe.**
It should be possible to write
```python
nixpkgs_cc_configure(
  repository = "@nixpkgs",
  nix_file_content = "(import <nixpkgs> {}).gcc11",
  name = "nixpkgs_config_cc",
)
``` 
as
```python
nixpkgs_cc_configure(
  repository = "@nixpkgs",
  attribute_path = "gcc11",
  name = "nixpkgs_config_cc",
)
```

**Describe the solution you'd like**
The `attribute_path` should be drawn from the `repository` if neither of `nix_file{,_content}` is given.

**Describe alternatives you've considered**

**Additional context**

**Comment by z8v** [comment]
Closing this, since #334 was merged.
