### ISSUE TITLE
Guide suggests command that produces error

### ISSUE THREAD

**Issue by kourtni** [tweag/rules_nixpkgs#379]
**Describe the bug**
While attempting to follow https://github.com/tweag/rules_nixpkgs/blob/master/guide.md I got an error when I entered the command `nix develop` after creating the `flake.nix` file in my repository. I have the same version of nix installed as is detailed in the guide: `nix (Nix) 2.13.2`. I am running this on Ubuntu on WSL.

**To Reproduce**
1. Create the flake.nix file as detailed.
2. run the following command: `nix develop`
3. See error that is generated:
`error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override`

**Expected behavior**
The `nix develop` command should not result in an error.

**Environment**
 - OS name + version: Ubuntu 22.04.1 LTS on WSL2 (Windows 11)
 - Version of the code: nix (Nix) 2.13.2

**Additional context**
None

**Comment by aherrmann** [comment]
Thanks for raising this! I believe the guide should also provide instructions to enable this experimental feature.
E.g. by adding
```
experimental-features = nix-command flakes
```
to `~/.config/nix/nix.conf`.
