### ISSUE TITLE
How to use rules_nixpkgs for python packages

### ISSUE THREAD

**Issue by smukherj1** [tweag/rules_nixpkgs#39]
Hi repo owners & @mboes,

I'm from the remote build execution team at Google and we are evaluating nix as a hermetic package manager for remote builds. I'm trying to create a project that uses rules_nixpkgs to download the flask python package and use it in a python hello world server app. 

I created https://github.com/smukherj1/eval_nixpkgs. This project has a Dockerfile that creates a container with bazel and the nix package manager. I have a script "docker_run.sh" which takes a single argument which should be the name of the image created by the Dockerfile. Note that this script needs to be in your current directory when you execute it. The script tries to build the python app using bazel in a docker container.

Currently, I get the following error:-
`ERROR: Analysis of target '//:app' failed; build aborted: no such package '@python2.7-Flask-1.0.2//': Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/ec321eb2cc2d0f8f91b676b6d4c66c29/external/io_tweag_rules_nixpkgs/nixpkgs/nixpkgs.bzl", line 82
                ":".join([((path_name + "=") + str(ctx.pa...()])
        File "/root/.cache/bazel/_bazel_root/ec321eb2cc2d0f8f91b676b6d4c66c29/external/io_tweag_rules_nixpkgs/nixpkgs/nixpkgs.bzl", line 83, in ":".join
                str(ctx.path(target))
        File "/root/.cache/bazel/_bazel_root/ec321eb2cc2d0f8f91b676b6d4c66c29/external/io_tweag_rules_nixpkgs/nixpkgs/nixpkgs.bzl", line 83, in str
                ctx.path(target)
Not a regular file: /workdir/external/nixpkgs
`

Now this is almost certainly because I created the bazel project wrong. Any guidance on where I went wrong would be greatly appreciated!

Thanks in advance for your help :)

**Comment by mboes** [comment]
@smukherj1 Can you confirm? If so we can close this ticket.

**Comment by smukherj1** [comment]
@mboes Yes confirming my test project built successfully when I implemented your suggestions. Thanks for the help! Sorry for forgetting to follow up here
