### ISSUE TITLE
In guide.md: "toolchain-resolution-debug" should use underscores

### ISSUE THREAD

**Issue by yikelu** [tweag/rules_nixpkgs#403]
I was following along with the guide and had one problem:
```
bash:~/dev/bazel-nix-ex$ bazel --version
bazel 5.4.1- (@non-git)
bash:~/dev/bazel-nix-ex$ bazel build //src:hello-world --toolchain-resolution-debug '.*'
ERROR: --toolchain-resolution-debug :: Unrecognized option: --toolchain-resolution-debug
```

Switching the dashes to underscores fixes this:
```
~/dev/bazel-nix-ex$ bazel build //src:hello-world --toolchain_resolution_debug '.*'
```

I didn't think a fork+PR was appropriate for this size of problem. Cheers.

**Comment by benradf** [comment]
Thanks for reporting this @yikelu. I've now [fixed it](https://github.com/tweag/rules_nixpkgs/commit/47a39a28c18b57bcbeae6d51e026f2601978d1d9).
