### ISSUE TITLE
Provide rules_pkg rpmbuild and git toolchain

### ISSUE THREAD

**Issue by malt3** [tweag/rules_nixpkgs#412]
**Is your feature request related to a problem? Please describe.**

rules_pkg depends on a rpmbuild toolchain to be available to package binaries as rpms in the [pkg_rpm rule](https://github.com/bazelbuild/rules_pkg/blob/main/docs/latest.md#pkg_rpm).
There is a method to load rpmbuild from the host path (which is non-hermetic).

EDIT: rules_pkg also has a git toolchain. I think we could provide that as well. The same points apply.

**Describe the solution you'd like**

nixpkgs [contains rpmbuild](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/package-management/rpm/default.nix) and could provide a rpmbuild toolchain as required by rules_pkg.

**Describe alternatives you've considered**

- Not provide rpmbuild via rules_nixpkgs and have failing builds if developers don't have it on their system
- Package rpmbuild myself

**Additional context**

I would be happy to implement this (if the maintainers like the idea).

**Comment by benradf** [comment]
Hi @malt3, thanks for your interest in adding this functionality.

A pull request would be welcome. I'd suggest putting the new toolchains under `toolchains/pkg/`, and if you have the time to add an example as well, that would be great.

**Comment by malt3** [comment]
I no longer need this, so closing for now.
If someone else has a need for it, feel free to reopen!
