### ISSUE TITLE
No such attribute `exec_constraints` on repo rule `_nixpkgs_package`

### ISSUE THREAD

**Issue by Wyverald** [tweag/rules_nixpkgs#416]
**Describe the bug**
Building using Bazel at HEAD (which contains https://github.com/bazelbuild/bazel/commit/4686e2550f76189cb1cfbe0852feb3337f38139c), we get the following error:

```
ERROR: /var/lib/buildkite-agent/builds/bk-docker-39vb/bazel-downstream-projects/rules_haskell/WORKSPACE:51:13: //external:rules_haskell_sh_posix_nixpkgs: no such attribute 'exec_constraints' in '_nixpkgs_package' rule
```

It's very scarce on details, but the call stack looks like this:

```
# Rule rules_haskell_sh_posix_nixpkgs instantiated at (most recent call last):
#   /usr/local/google/home/wyv/github/rules_haskell/WORKSPACE:51:13                                                                    in <toplevel>
#   /usr/local/google/home/wyv/github/rules_haskell/non_module_dev_deps.bzl:76:33                                                      in repositories
#   /usr/local/google/home/wyv/github/rules_haskell/haskell/nixpkgs.bzl:411:31                                                         in haskell_register_ghc_nixpkgs
#   /usr/local/google/home/wyv/.cache/bazel/_bazel_wyv/3a07f8d42f5e075b1524c733ca45f269/external/rules_nixpkgs_posix/posix.bzl:163:28  in nixpkgs_sh_posix_configure
#   /usr/local/google/home/wyv/.cache/bazel/_bazel_wyv/3a07f8d42f5e075b1524c733ca45f269/external/rules_nixpkgs_posix/posix.bzl:23:20   in nixpkgs_sh_posix_config
#   /usr/local/google/home/wyv/.cache/bazel/_bazel_wyv/3a07f8d42f5e075b1524c733ca45f269/external/rules_nixpkgs_core/nixpkgs.bzl:676:21 in nixpkgs_package
# Rule _nixpkgs_package defined at (most recent call last):
#   /usr/local/google/home/wyv/.cache/bazel/_bazel_wyv/3a07f8d42f5e075b1524c733ca45f269/external/rules_nixpkgs_core/nixpkgs.bzl:549:35 in <toplevel>
```

This problem starts from around here: https://github.com/tweag/rules_nixpkgs/blob/43066717fb694c8ab8ad1d617c97e2a86fec5a97/toolchains/posix/posix.bzl#L163

If `exec_constraints` is specified, you'll eventually run into problems down the line.

**To Reproduce**
```sh
git clone https://github.com/tweag/rules_haskell
git checkout f801bba2773ae2fde30e0da2138f6ac0f2c2a910 # rules_haskell at HEAD is broken differently
USE_BAZEL_VERSION=last_green bazel info
```

**Expected behavior**
Nothing fails.

**Environment**
 - OS name + version: Debian rolling
 - Version of the code: current HEAD

**Additional context**
This should ideally be fixed before Bazel 7.

**Comment by avdv** [comment]
@Wyverald I just noticed that we also see this problem when using rules_nixpkgs < 0.10 with Bazel 6.4.0. This means https://github.com/bazelbuild/bazel/commit/4686e2550f76189cb1cfbe0852feb3337f38139c (ie. https://github.com/bazelbuild/bazel/commit/556396fb7157e3bb4306ff780aa8c72f6ee6831a) broke backward compatibility; `--noincompatible_fail_on_unknown_attributes` also seems to have no effect.

Is that expected, or should I open a new issue about it?
