### ISSUE TITLE
rules_go now requires `rulesGoStdlibPrefix` to be set via `-X`

### ISSUE THREAD

**Issue by malt3** [tweag/rules_nixpkgs#421]
**Describe the bug**

`rules_go` is planning a new release (0.42). This new release will contain the following change: https://github.com/bazelbuild/rules_go/pull/3701.

It leads to this error when using the go toolchain provided by rules_nixpkgs:

```
ERROR: /home/malte/.cache/bazel/_bazel_malte/bb1175a64d2f0f71785aea697a0484ea/external/io_bazel_rules_go/BUILD.bazel:42:7: GoStdlib external/io_bazel_rules_go/stdlib_/pkg failed: (Exit 2): builder failed: error executing command (from target @io_bazel_rules_go//:stdlib) 
  (cd /home/malte/.cache/bazel/_bazel_malte/bb1175a64d2f0f71785aea697a0484ea/sandbox/linux-sandbox/80/execroot/constellation && \
  exec env - \
    CGO_ENABLED=0 \
    GOARCH=amd64 \
    GOEXPERIMENT='' \
    GOOS=linux \
    GOPATH='' \
    GOROOT=external/go_sdk \
    GOROOT_FINAL=GOROOT \
    GOTOOLCHAIN=local \
    PATH=external/zig_sdk/tools:external/zig_sdk/tools/x86_64-linux-gnu.2.23:/bin:/usr/bin \
  bazel-out/k8-opt-exec-C7777A24-ST-e336f88b9a0e/bin/external/go_sdk/builder stdlib -sdk external/go_sdk -installsuffix linux_amd64 -tags netgo,netgo -out bazel-out/k8-opt-ST-04e6e76229c2/bin/external/io_bazel_rules_go/stdlib_ -package std -gcflags '')
# Configuration: 4114e72d42dffca035c92c4853a59204220a10d133544398bcba8b927789b8dc
# Execution platform: @rules_nixpkgs_core//platforms:host

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
panic: rulesGoStdlibPrefix should have been set via -X

goroutine 1 [running]:
main.init.0()
        ./stdliblist.go:113 +0x31
```

**To Reproduce**
Steps to reproduce the behavior.

Use `rules_go` >= https://github.com/bazelbuild/rules_go/commit/c2406b27f77e186d0fb3548d8526e6c14a3236d4
And rules_nixpkgs with `nixpkgs_go_configure`.

**Expected behavior**

Builds should succeed.

**Environment**
 - OS name + version: Ubuntu 22.04
 - Version of the code: 7e627d76ba65d6c42586fc265e46bd370672b4eb

**Additional context**

Happy to provide a fix. As of now, I just don't understand where to take the stdlib prefix from (or if `rules_nixpkgs` even provides this)

**Comment by DolceTriade** [comment]
For now, we just use this as a local patch which isn't great.

Do you think we can use https://github.com/bazelbuild/rules_go/blob/4211c6d32ee475a8fde1cfc91571e7c0bed67af4/go/def.bzl#L122

to optionally add the extra ldflag or not?

maybe something like (untested...)
```
load(@{rules_go}//go/def.bzl, "RULES_GO_VERSION")

go_tool_binary(
    name = "builder",
    srcs = ["@{rules_go}//go/tools/builders:builder_srcs"],
    ldflags = "-X main.rulesGoStdlibPrefix=@{rules_go}//stdlib:" if int(RULES_GO_VERSION.split(".")[1]) >= 42 else "",
    sdk = ":go_sdk",
)
```

**Comment by malt3** [comment]
Something like that may work. This is certainly not something you want to maintain forever, but maybe we could add this with a note that it should be removed after some grace period?
We could even print a warning from Starlark if an old rules_go version is detected.
