### ISSUE TITLE
asan doesn't work with nixpkgs cc toolchain

### ISSUE THREAD

**Issue by iphydf** [tweag/rules_nixpkgs#430]
**Describe the bug**
When compiling with `-fsanitize=address`, I get the following error:

```
ERROR: /home/builder/.cache/bazel/_bazel_builder/a08c2e4811c846650b733c6fc815a920/external/com_google_googletest/BUILD.bazel:80:11: Compiling googletest/src/gtest-assertion-result.cc failed: undeclared inclusion(s) in rule '@com_google_googletest//:gtest':
this rule is missing dependency declarations for the following files included by 'googletest/src/gtest-assertion-result.cc':
  '/nix/store/9k6s3zmhj2pvkg8a5s8n7d2sbpffv8hv-clang-wrapper-16.0.1/resource-root/share/asan_ignorelist.txt'
```

**To Reproduce**
Compile with `-fsanitize=address`.

**Expected behavior**
Compilation should succeed.

**Environment**
 - OS name + version: Ubuntu 22.04 with nixpkgs 23.05.
 - Version of the code: 7e627d76ba65d6c42586fc265e46bd370672b4eb

**Additional context**
This is the repo: https://github.com/TokTok/toktok-stack

It's a little complicated. I haven't tried reproing on a smaller test case.

**Comment by avdv** [comment]
Hi @iphydf, I have create a fix here: #437 In the meantime, I think you could work around with passing `-fno-sanitize-ignorelist` which would inhibit using the system ignorelist file (depending on how important that file's content is).
