### ISSUE TITLE
Publish to BCR app failed

### ISSUE THREAD

**Issue by aherrmann** [tweag/rules_nixpkgs#434]
**Describe the bug**
I've configured the [publish to BCR app](https://github.com/bazel-contrib/publish-to-bcr) for rules_nixpkgs before release 0.10.0. After the release I received a failure notification from the app:

> Failed to publish entry for tweag/rules_nixpkgs@v0.10.0 to the Bazel Central Registry.
>
> An unknown error occurred. Please report an issue here: https://github.com/bazel-contrib/publish-to-bcr/issues.

I've commented on a [corresponding already open issue](https://github.com/bazel-contrib/publish-to-bcr/issues/44#issuecomment-1770262701).

Once we have an understanding of what's wrong with the configuration, we can correct the mistake.

**To Reproduce**
Cut a release? I'm not aware of a better way to reproduce the issue.

**Expected behavior**
The publish to BCR app should have created a PR to add the release to the BCR as expected.

**Environment**
 - OS name + version: n/a
 - Version of the code: 0.10.0

**Additional context**
none

**Comment by kormide** [comment]
There's an error in `.bcr/core/source.template.json`. See post in https://github.com/bazel-contrib/publish-to-bcr/issues/44.
