### ISSUE TITLE
rules_nixpkgs broken with the latest rules_go

### ISSUE THREAD

**Issue by DolceTriade** [tweag/rules_nixpkgs#436]
**Describe the bug**
If you try to build a go using rules_nixpkgs and rules_go 0.42.0, the rules_go builder will panic with:
```
rulesGoStdlibPrefix should have been set via -X
```

**To Reproduce**
Build any go package with rules_nixpkgs and rules_go 0.42.0

**Expected behavior**
Not panic

**Additional context**
```
diff --git a/toolchains/go/go.bzl b/toolchains/go/go.bzl
index cb0f26a..179cd9c 100644
--- a/toolchains/go/go.bzl
+++ b/toolchains/go/go.bzl
@@ -212,6 +212,7 @@ go_sdk_build = """
 load("@{rules_go}//go/private/rules:binary.bzl", "go_tool_binary")
 load("@{rules_go}//go/private/rules:sdk.bzl", "package_list")
 load("@{rules_go}//go:def.bzl", "go_sdk")
+load("@{rules_go}//go/private:common.bzl", "RULES_GO_STDLIB_PREFIX")
 load("@{helpers}//:go_sdk.bzl", "go_sdk_for_arch")
 load(":go_version.bzl", "go_version")

@@ -237,6 +238,7 @@ filegroup(
 go_tool_binary(
     name = "builder",
     srcs = ["@{rules_go}//go/tools/builders:builder_srcs"],
+    ldflags = "-X main.rulesGoStdlibPrefix=%s"% RULES_GO_STDLIB_PREFIX,
     sdk = ":go_sdk",
 )

--
2.39.2
```

Fixes the issue.

https://github.com/bazelbuild/rules_go/commit/c2406b27f77e186d0fb3548d8526e6c14a3236d4 makes the change.

The reason this is an issue and not a PR because I'm not sure the best way to handle this change across different rules_go versions.

**Comment by malt3** [comment]
There is this PR but I'm also very much uncertain how to handle this breaking change #422

**Comment by DolceTriade** [comment]
We can dupe this then.
