### ISSUE TITLE
Cannot switch cxx standard

### ISSUE THREAD

**Issue by antholeole** [tweag/rules_nixpkgs#484]
I'm trying to use a c++ project with [absl](https://github.com/abseil/abseil-cpp), but the compile keeps failing on bad cxx version:

```
external/com_google_absl/absl/base/policy_checks.h:79:2: error: "C++ versions less than C++14 are not supported."                                       
#error "C++ versions less than C++14 are not supported."                                                                                                
 ^                                                                                                                                                      
1 error generated.     
``` 

my WORKSPACE file looks pretty much like the intro-one in the readme. here is the build rule (just a dummy one):

```
cc_library(
    name = "test_cc",
    copts = [
        "-std=c++17"
    ],
    deps = [
        "@com_google_absl//absl/log",
    ],
)
```

I see that we hardcode `-std=c++0x` in [cc.nix](https://github.com/tweag/rules_nixpkgs/blob/9b13ed0469116a37658040a7b62d70aea90ad0bc/toolchains/cc/cc.nix#L203). Is there a canonical way to change it, or would a PR we accepted to add this as a flag to configure cc toolchain? Thanks! 

apologies if I just am not nixing correctly and there is a nix solution to this.

**Comment by antholeole** [comment]
Ah I was misguided - I selected the wrong compiler.

```
nixpkgs_cc_configure(
    name = "nixpkgs_config_cc",
    attribute_path = "llvmPackages_17.libcxxClang",
    repository = "@nixpkgs",
)
```

worked. thanks for the repo!

**Comment by benradf** [comment]
Glad you were able to resolve the problem!
