### ISSUE TITLE
Publish to BCR failed

### ISSUE THREAD

**Issue by aherrmann** [tweag/rules_nixpkgs#490]
**Describe the bug**
> Failed to publish entry for tweag/rules_nixpkgs@v0.11.0 to the Bazel Central Registry.
>
> Invalid metadata template file /tmp/cbdc5835-ee64-46c5-9151-5e1cace20f00/rules_nixpkgs/.bcr/core/metadata.template.json: Could not read metadata file at /tmp/cbdc5835-ee64-46c5-9151-5e1cace20f00/rules_nixpkgs/.bcr/core/metadata.template.json: could not parse 'yanked_versions'

**To Reproduce**
n/a. Automated email sent by Publish to BCR automation.

**Expected behavior**
Automatic Publish to BCR should have succeeded

**Environment**
 - OS name + version: n/a
 - Version of the code: 0.11.0

**Additional context**
n/a

cc @prednaz @avdv @benradf

**Comment by avdv** [comment]
Unfortunately, there is no way to trigger the app except of creating a new release. Could you take care of creating a PR to https://github.com/bazelbuild/bazel-central-registry/ manually @prednaz ?

**Comment by prednaz** [comment]
> Could you take care of creating a PR to https://github.com/bazelbuild/bazel-central-registry/ manually @prednaz ?

yes, on it!

**Comment by prednaz** [comment]
i talked to @cgrindel and we [fixed `.bcr/core/metadata.template.json`](https://github.com/tweag/rules_nixpkgs/pull/491). would you mind if we triggered publish-to-bcr again with a patch release 0.11.1?

**Comment by avdv** [comment]
> i talked to @cgrindel and we made [a small fix to `.bcr/core/metadata.template.json`](https://github.com/tweag/rules_nixpkgs/pull/491). would you mind if we triggered publish-to-bcr again with a patch release 0.11.1?

Go for it! :+1:
