### ISSUE TITLE
examples in `examples/toolchains` use a platform provided cc toolchain

### ISSUE THREAD

**Issue by prednaz** [tweag/rules_nixpkgs#501]
**Describe the bug**
i believe, the examples in `examples/toolchains` use a platform provided cc toolchain instead of a `rules_nixpkgs` provided one, as claimed by https://github.com/tweag/rules_nixpkgs/pull/286.

**To Reproduce**
executing `cd examples/toolchains/go && nix-shell --command 'bazel run --config=nix :hello'` on nixos fails with `Auto-Configuration Error: Cannot find gcc or CC; either correct your path or set the CC environment variable`.

turning `nix-shell` into `nix-shell --pure` in [`.github/workflows/workflow.yaml`](https://github.com/tweag/rules_nixpkgs/pull/500/files#diff-fde0e5d64aae13964fdda6d47af304cf1a7015cbc17e440ac4a5e662ee1d875e) causes ci to fail with the same error message too as demonstrated with https://github.com/tweag/rules_nixpkgs/pull/500.

**Expected behavior**
if the cc toolchain was provided by `rules_nixpkgs`, switching to nixos or `nix-shell --pure` should not prevent bazel from finding "gcc or CC".

**Environment**
 - OS name + version: NixOS 23.11.4080.fb0c047e30b6 (Tapir) x86_64
 - Version of the code: [`126e9f6`](https://github.com/tweag/rules_nixpkgs/tree/126e9f66b833337be2c35103ce46ab66b4e44799)

**Comment by avdv** [comment]
> if the cc toolchain was provided by `rules_nixpkgs`, switching to nixos or `nix-shell --pure` should not prevent bazel from finding "gcc or CC".

Bazel will always try to configure a system toolchain, except if the `BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN` environment variable is set to `1`.

When using a pure nix-shell, that variable is not going to be set and thus auto-configuration will fail. We should set this variable as part of the `.bazelrc` in the repo env.

**Comment by avdv** [comment]
Closing, since the problem in #500 was resolved.
