### ISSUE TITLE
Why is `nixpkgs_package` marked as `local`

### ISSUE THREAD

**Issue by regnat** [tweag/rules_nixpkgs#52]
The `nixpkgs_package` rule has `local = True`, which means that it will be re-executed each time something changes anywhere in the workspace.
This is very costly since evaluating them can take a long time and they should be pure.
Is there any reason for this?

According to `git blame`, it has been introduced as part of https://github.com/tweag/rules_nixpkgs/commit/4b63a7edeee5c1a83636de9376405f0e9116892d.

/cc @mboes

**Comment by mboes** [comment]
I think it's because `nixpkgs_package` typically depends on a `nixpkgs_{git,local}_repository`. According to the Bazel docs:

> If the repository is declared as local then change in a dependency in the dependency graph (including the WORKSPACE file itself) will cause an execution of the implementation function.

In our case, a package should be reevaluated if the repository changes. So we need `local = True`, don't we?

**Comment by regnat** [comment]
closed by #53
