### ISSUE TITLE
"no such target" error until i do a "bazel clean --expunge"

### ISSUE THREAD

**Issue by blockjon-dd** [tweag/rules_nixpkgs#594]
**Describe the bug**
I often have to do a `bazel clean --expunge` to get a nix flake to work.

**To Reproduce**
I've got this in my WORKSPACE.bzlmod
```
http_archive(
    name = "io_tweag_rules_nixpkgs",
    sha256 = "1adb04dc0416915fef427757f4272c4f7dacefeceeefc50f683aec7f7e9b787a",
    strip_prefix = "rules_nixpkgs-0.12.0",
    urls = ["https://github.com/tweag/rules_nixpkgs/releases/download/v0.12.0/rules_nixpkgs-0.12.0.tar.gz"],
)

load("@io_tweag_rules_nixpkgs//nixpkgs:repositories.bzl", "rules_nixpkgs_dependencies")
rules_nixpkgs_dependencies()

load("@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl", "nixpkgs_cc_configure", "nixpkgs_flake_package", "nixpkgs_git_repository", "nixpkgs_package", "nixpkgs_python_configure")

nixpkgs_flake_package(
    name = "awscli",
    nix_flake_file = "//tools/aws:flake.nix",
    nix_flake_lock_file = "//tools/aws:flake.lock",
    package = "awscli2",
)
```
and then I have a genrule that tries to use this to access the aws cli like this:
```
genrule(
    name = "aws",
    srcs = ["@awscli//:bin/aws"],
    outs = ["awscli/aws"],
    executable = True,
    cmd = "cp $(<) $@",
)
```
The problem is that sometimes, when I try to run the aws cli, I get the following error:
```
$ bazel run //tools/aws
INFO: Invocation ID: ad4619e8-2e0b-4c86-95f4-6d9a9d77daa7
WARNING: For repository 'platforms', the root module requires module version platforms@0.0.9, but got platforms@0.0.10 in the resolved dependency graph.
ERROR: /home/dev/.cache/bazel/_bazel_dev/d3a77f884815e44a5c8f13a771dbf3a4/external/awscli/BUILD: no such target '@@awscli//:bin/aws': target 'bin/aws' not declared in package '' defined by /home/dev/.cache/bazel/_bazel_dev/d3a77f884815e44a5c8f13a771dbf3a4/external/awscli/BUILD
ERROR: /workspaces/pedregal/tools/aws/BUILD.bazel:1:8: no such target '@@awscli//:bin/aws': target 'bin/aws' not declared in package '' defined by /home/dev/.cache/bazel/_bazel_dev/d3a77f884815e44a5c8f13a771dbf3a4/external/awscli/BUILD and referenced by '//tools/aws:aws'
ERROR: Analysis of target '//tools/aws:aws' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.321s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
ERROR: Build failed. Not running target
```
if I do a `bazel clean --expunge`, it works:

```
$ bazel run //tools/aws
...
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

aws: error: the following arguments are required: command
```

**Expected behavior**
Things work without the need to run the expunge command.

**Environment**
 - Linux 352246c5cbfe 6.10.4-linuxkit  SMP Mon Aug 12 08:47:01 UTC 2024 aarch64 GNU/Linux
 - Inside of a devbox
 - bazel 7.3.1
 - rules_nixpkgs 0.12.0

**Comment by avdv** [comment]
That seems to be caused by a garbage collection of the nix store, which invalidates the symlink pointing to awscli.

If that happens again, could you run `ls -lh $(bazel info output_base)/external/awscli` to see where the symlinks point to and also if  they are still valid?

Now, this should actually not happen, since a gcroot entry is created by `nixpkgs_flake_package` to retain the store path that the `awscli` repository references. Have you enabled garbage collection of the nix store? (or maybe devbox does that somehow?) 

If that happens again, could you check the symlinks in [gcroots](https://nix.dev/manual/nix/2.18/package-management/garbage-collector-roots.html) to see if there is one pointing back into the `awscli` repository directory?

Also, which nix version do you use?

**Comment by blockjon-dd** [comment]
I think this problem relates to how devbox works. I think we just need to somehow have the /nix/store directory survive a restart of the devbox.

Here's how to repro it:

1. Use the aws cli once `bazel run //tools/aws`
  _(at this point, `/nix/store/san7pp6b1ry1qgnn20hih3q77hfkw251-awscli2-2.15.43/bin/aws` exists)_
3. Exit the dev container and stop it
4. Start the dev container
5. Enter the dev container and try to run the command again `bazel run //tools/aws`

When I re-enter the devcontainer, the symlinks that were created in step 1 are still there, but the locations where they point to are not.

```
$ ls -lh $(bazel info output_base)/external/awscli
INFO: Invocation ID: 62b88a79-cc3c-4c0b-ba18-bcb7a6d7b271
total 32K
drwxr-xr-x  3 dev dev 4.0K Sep 19 19:34 .
drwxr-xr-x 22 dev dev 4.0K Sep 19 19:34 ..
drwxr-xr-x  2 dev dev 4.0K Sep 19 19:34 bazel-support
lrwxrwxrwx  1 dev dev   63 Sep 19 19:34 bin -> /nix/store/san7pp6b1ry1qgnn20hih3q77hfkw251-awscli2-2.15.43/bin
-rwxr-xr-x  1 dev dev  405 Sep 19 19:34 BUILD
lrwxrwxrwx  1 dev dev   63 Sep 19 19:34 lib -> /nix/store/san7pp6b1ry1qgnn20hih3q77hfkw251-awscli2-2.15.43/lib
lrwxrwxrwx  1 dev dev   71 Sep 19 19:34 nix-support -> /nix/store/san7pp6b1ry1qgnn20hih3q77hfkw251-awscli2-2.15.43/nix-support
-rw-r--r--  1 dev dev    0 Sep 19 19:34 REPO.bazel
lrwxrwxrwx  1 dev dev   65 Sep 19 19:34 share -> /nix/store/san7pp6b1ry1qgnn20hih3q77hfkw251-awscli2-2.15.43/share
-rw-r--r--  1 dev dev    0 Sep 19 19:34 WORKSPACE
```
here you can see the file is not present anymore:
```
$ /nix/store/san7pp6b1ry1qgnn20hih3q77hfkw251-awscli2-2.15.43/bin/aws
-bash: /nix/store/san7pp6b1ry1qgnn20hih3q77hfkw251-awscli2-2.15.43/bin/aws: No such file or directory
```

**Comment by blockjon-dd** [comment]
The guidance I just got is instead of "mapping" /nix/store to the host (as I had assumed I wanted), that we should change the settings of nix to store it in the home dir, which does survive and is machine specific.

I'm sure that's a 1-liner config file I need to put somewhere, just not sure where yet...

**Comment by aherrmann** [comment]
I'm glad to hear that you found a path forward for this!

> I'm sure that's a 1-liner config file I need to put somewhere, just not sure where yet...

If you find the relevant configuration, if you could also share it here for later reference that would help others who run into the same issue.
