### ISSUE TITLE
rules_nixpkgs interacts badly with cc_import on Linux

### ISSUE THREAD

**Issue by aherrmann** [tweag/rules_nixpkgs#60]
Trying to execute a `cc_binary` that depends on a `cc_import` based on a `nixpkgs_package` is likely to fail due to missing files in Bazel's generated `_solib` directory.

Consider the following example. (Provided in full detail in https://github.com/tweag/rules_nixpkgs/commit/22fbc2facb35e1a46773d191a3db3f3429d089f5.)

First, we import `libz.so` from nixpkgs:
```
nixpkgs_package(
    name = "zlib",
    repository = "@nixpkgs",
)
```
Then, we use `cc_import` to import the shared object:
```
cc_import(
    name = "z-lib",
    shared_library = "@zlib//:lib/libz.so",
)
```
Finally, we define a `cc_binary` (or `cc_test`) that depends on the library:
```
cc_binary(
    name = "cc-import-test",
    srcs = ["cc-import-test.cc"],
    deps = [":z-lib"],
)
```
If we try to execute that binary on Linux (`bazel test //tests:cc-import-test` on https://github.com/tweag/rules_nixpkgs/commit/22fbc2facb35e1a46773d191a3db3f3429d089f5) it will fail with the following dynamic linking error:
```
libz.so.1: cannot open shared object file: No such file or directory
```
The reason is that the generated binary will refer to the library under its soname `libz.so.1`, but the `RUNPATH` will only contain the symbolic link `libz.so` which points to the soname version.
```
$ readelf -d bazel-bin/tests/cc-import-test
...
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
...
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../_solib_k8/_U_S_Stests_Cz-lib___Uexternal_Szlib_Slib:...]
...
$ ls bazel-out/k8-fastbuild/bin/tests/cc-import-test.runfiles/io_tweag_rules_nixpkgs/_solib_k8/_U_S_Stests_Cz-lib___Uexternal_Szlib_Slib/
libz.so
```

A work-around is to use `cc_library` instead of `cc_import` and pass all names of the shared object into the `srcs` attribute:
```
cc_library(
    name = "z-workaround",
    srcs = ["@zlib//:lib"],
)
```
The resulting binary (`bazel test //tests:cc-import-workaround` on https://github.com/tweag/rules_nixpkgs/commit/22fbc2facb35e1a46773d191a3db3f3429d089f5) will still refer to `libz.so.1`, but the corresponding `_solib` directory will contain that file:
```
$ readelf -d bazel-bin/tests/cc-import-workaround
...
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
...
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../_solib_k8/_U_S_Stests_Cz-workaround___Uexternal_Szlib_Slib:...]
...
$ ls bazel-bin/tests/cc-import-workaround.runfiles/io_tweag_rules_nixpkgs/_solib_k8/_U_S_Stests_Cz-workaround___Uexternal_Szlib_Slib/
libz.so  libz.so.1  libz.so.1.2.11
```

This begs the question: Why not always use `cc_library` instead of `cc_import`? `cc_library` resolves the soname issue described above, and also resolves the `strip_include_prefix` issue as pointed out [here](https://github.com/bazelbuild/bazel/issues/4748#issuecomment-370707938).

**Comment by mboes** [comment]
> This begs the question: Why not always use cc_library instead of cc_import?

That's a really good question. I think you should submit it to bazel-discuss@.

**Comment by Profpatsch** [comment]
Has this been fixed by the new `CCInfo` provider API in bazel?

**Comment by aherrmann** [comment]
It's easy to work around the issue using `cc_library`. (As the rules_haskell docs now advertise.) It's really an issue in `cc_import` itself. So, I'll close this as there's not much we can do in rules_nixpkgs.
