### ISSUE TITLE
almost all of `@bazel_tools//tools/cpp` may not exist for Bazel@8.0.0rc4

### ISSUE THREAD

**Issue by kczulko** [tweag/rules_nixpkgs#612]
Hello,

I've just received an email from bazelbuild/bazel-central-registry saying that the module I maintain contains errors for Bazel@8.0.0rc4. The build output says that [this import](https://github.com/tweag/rules_nixpkgs/blob/668609f0b3627751651cb325166d0e95062be3f7/core/util.bzl#L1) may not exist.

Build run: https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/72#019367bc-a445-4f6b-8c2b-0413f2287689

Error message:
```
(09:32:44) ERROR: Traceback (most recent call last):
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/5d027fa2b9037dc8b327099b176cebb0/external/rules_nixpkgs_core+/util.bzl", line 1, column 55, in <toplevel>
		load("@bazel_tools//tools/cpp:lib_cc_configure.bzl", "get_cpu_value")
Error: file '@bazel_tools//tools/cpp:lib_cc_configure.bzl' does not contain symbol 'get_cpu_value'
(09:32:44) ERROR: Analysis of target '//:spec' failed; build aborted: Error loading '@@rules_nixpkgs_core+//extensions:package.bzl' for module extensions, requested by /var/lib/buildkite-agent/builds/bk-docker-2fzt/bazel-org-repo-root/output/rules_elm-1.0.1/examples/elm-test/MODULE.bazel:105:24: at /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/5d027fa2b9037dc8b327099b176cebb0/external/rules_nixpkgs_core+/extensions/package.bzl:6:6: at /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/5d027fa2b9037dc8b327099b176cebb0/external/rules_nixpkgs_core+/nixpkgs.bzl:36:5: initialization of module 'util.bzl' failed: at /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/5d027fa2b9037dc8b327099b176cebb0/external/rules_nixpkgs_core+/extensions/package.bzl:6:6: at /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/5d027fa2b9037dc8b327099b176cebb0/external/rules_nixpkgs_core+/nixpkgs.bzl:36:5: initialization of module 'util.bzl' failed
```

Helpful links:
- [commit](https://github.com/bazelbuild/bazel/commit/1c4e78a9ceab9794140324d64833c628e382a3da) where `@bazel_tools//tools/cpp` was moved away
- [commit](https://github.com/bazelbuild/rules_cc/commit/c2549f6eb07ce00e529b84f9b9f1b31135a9ff77) where the same code was added to rules_cc

**Comment by kczulko** [comment]
Hi @malt3 

Sure, I may give it a try in my spare time. Thx for the hints!

Best regards,
Karol

**Comment by malt3** [comment]
I noticed that most of that package was deleted.

Here a list of components I will migrate:

- [ ] many symbols from `@bazel_tools//tools/cpp:lib_cc_configure.bzl`
- [ ] @bazel_tools//tools/cpp:BUILD.tpl
- [ ] @bazel_tools//tools/cpp:armeabi_cc_toolchain_config.bzl
- [ ] @bazel_tools//tools/cpp:generate_system_module_map.sh
- [ ] @bazel_tools//tools/cpp:osx_cc_wrapper.sh.tpl
- [ ] @bazel_tools//tools/cpp:linux_cc_wrapper.sh.tpl

We can vendor them from [rules_cc](https://github.com/bazelbuild/rules_cc/tree/5be90a4e04e64df0e9d26382e1006d3df21aaa91/cc/private/toolchain).
