### ISSUE TITLE
nixpkgs_local_repository nix_file_deps is mangled

### ISSUE THREAD

**Issue by robinp** [tweag/rules_nixpkgs#71]
I have 
```
nixpkgs_local_repository(
    name = "nixpkgs",
    nix_file = "//nix:nixpkgs.nix",
    nix_file_deps = [
        "//nix:fetch.nix",
    ],
```
which seems to end up in the bazel cache as:
```
$ ls ...../external/nixpkgs
BUILD  nixpkgs  nixpkgs.nix  nix_Sfetch.nix  WORKSPACE
```

**Comment by Profpatsch** [comment]
Yeah, that is a bug.

**Comment by regnat** [comment]
I don't think it is. These symlinks are just a hack to force the rule to depend on its inputs and are not meant to be consumed by anything. Why do you need them @robinp ?

**Comment by robinp** [comment]
@regnat I assumed if `nixpkgs.nix` wanted to do `import ./fetch.nix`. Is that invalid? Should the file be self-contained? But if so, what is the use of dependencies?

**Comment by regnat** [comment]
> I assumed if `nixpkgs.nix` wanted to do `import ./fetch.nix`. Is that invalid? Should the file be self-contained? But if so, what is the use of dependencies?

The `nixpkgs.nix` in the bazel cache is a symlink to the one in the repository, and in that case Nix will follow the paths relative to the *target* of the symlink. So `import ./fetch.nix` should work if `fetch.nix` is located near `nixpkgs.nix` in your source tree (but if it doesn't then that's definitely a bug)

**Comment by robinp** [comment]
Thanks for clarifying! My bad, I needed an extra level of indirection in one of those nix files.
