### ISSUE TITLE
Fix misc issues

### ISSUE THREAD

**Issue by Profpatsch** [tweag/rules_nixpkgs#72]
- [ ] https://github.com/tweag/rules_nixpkgs/pull/70#discussion_r258443281
- [ ] https://github.com/tweag/rules_nixpkgs/pull/70#discussion_r258443326
- [ ] https://github.com/tweag/rules_nixpkgs/pull/70#discussion_r258490688

**Comment by smelc** [comment]
@Profpatsch > I think this issue is deprecated since https://github.com/tweag/rules_nixpkgs/pull/70 did not got merged.
