### ISSUE TITLE
nixpkgs_package dependency change does not invalidate repository

### ISSUE THREAD

**Issue by guibou** [tweag/rules_nixpkgs#74]
This is a new variation of https://github.com/tweag/rules_nixpkgs/issues/17

`nixpkgs_package` allows users to list the nix dependencies using `nix_file_deps`, but that's of no help for reproducibility because `nixpkgs_package` will work even if the nix process depends on files not listed in `nix_file_deps`.

For example, the following won't be invalidated in case `foo.nix` dependencies change.

```
nixpkgs_package(
    name = "foo",
    attribute_path = "foo",
    repositories = {"nixpkgs": "//:foo.nix"},
)
```

**Comment by Profpatsch** [comment]
How about we set up a mount namespace (which only contains the listed nix files) before we run `nix`?

**Comment by guibou** [comment]
I'm afraid it won't be portable.

**Comment by Profpatsch** [comment]
Then let’s do a best-effort thing that works at least on linux and is a no-op on MacOS

**Comment by guibou** [comment]
@Profpatsch AFAIK mount / user namespace are not portable even on linux. For example, they are disabled by default on arch linux or in any docker container.

**Comment by guibou** [comment]
`nix-build -vv` gives a lot of informations. For example, if my `foo.nix` file references `nixpkgs.nix`, `overlay.nix`, `crosstool/default.nix`, `crosstool/CROSSTOOL.template`, I'm getting:

```
nix-build -vv ./kitty.nix -A kitty.crosstoolFile 2>&1 | grep home                                                                                   ~/kitty/heavisoft
evaluating file '/home/guillaume/blort/nixpkgs.nix'
evaluating file '/home/guillaume/.config/nixpkgs/config.nix'
evaluating file '/home/guillaume/blork/nix/overlay.nix'
evaluating file '/home/guillaume/blork/nix/autogen/crosstool/default.nix'
copied source '/home/guillaume/blork/nix/autogen/crosstool/CROSSTOOL.template' -> '/nix/store/175283332iaqcqkkj1464vr4l5bijrbm-CROSSTOOL.template'
```

I propose the following change of `nixpkgs_package`. After `nix-build`, we check the output for `evaluating file xxx` and `copied source xxx` and check that this set match the set provided as the argument `nix_dep_files` and fails if not.

It may be robust.

What do you think? Should we go this way? I can propose a pull request if you think this is the way to go.

-- 
G.

**Comment by Profpatsch** [comment]
> For example, they are disabled by default on arch linux or in any docker container.

In that case you also get problems with nix and sandboxed mode, which requires user namespaces to function.

**Comment by aherrmann** [comment]
For us this is a problem as well. Bazel not noticing Nix file changes can lead to increased Bazel distributed cache misses or subtle bugs or build failures if some version doesn't match the expectations. Having to keep `nix_file_deps` manually in sync is quite error prone.

> I propose the following change of nixpkgs_package. After nix-build, we check the output for evaluating file xxx and copied source xxx and check that this set match the set provided as the argument nix_dep_files and fails if not.

I think something like this would certainly be an improvement compared to the current situation.

I've noticed that files that are loaded using Nix's `builtins.readFile` are not necessarily listed in that output. So, the check should not fail if `nix_dep_files` lists more files than `nix-build -vv` prints out.

> Also, because of import-from-derivation I don’t think it makes sense to require all files that nix-build -vv lists, because that might also contain hundreds of nix files from e.g. a nixpkgs dependency.

That is true. The check should probably ignore files from the Nix store.

**Comment by guibou** [comment]
@aherrmann I'll try to push my PR with the sanity check described previously. That's better than nothing and we'll wait for upstream bazel answers for a sandboxing solution.
