### ISSUE TITLE
Random index of range error

### ISSUE THREAD

**Issue by guibou** [tweag/rules_nixpkgs#79]
**Describe the bug**

Since I upgraded rules_nixpkgs from `rules_nixpkgs-0.3.1` to `67a80de8648b2b40a3b7f5b4b8b7f2ad95c1a08c` we are experiencing random and weird issues with some bazel calls fails such as:

```
$ bazel build //...
INFO: Invocation ID: 7a93f2ef-0897-4ad2-b6ac-4171ccd78dd2
ERROR: /my/workspace/BUILD.bazel:13:1: no such package '@foo//': index out of range (index is 1, but sequence has 1 elements) and referenced by '//:bar'
ERROR: Analysis of target '//rat/crevette:chien' failed; build aborted: no such package '@foo//': index out of range (index is 1, but sequence has 1 elements)
INFO: Elapsed time: 10.505s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (12 packages loaded, 51 targets configured)
FAILED: Build did NOT complete successfully (12 packages loaded, 51 targets configured)
```

The build succeed if the command is ran another time. No `bazel clean` was necessary.

**To Reproduce**

I'm unable to consistently reproduce the issue. Initially I was tempted to think that it was something wrong in an internal state after the upgrade and that running bazel fixed it, but it appears to come back sometimes. I don't know what triggers it. I can do a full bisect on the codebase jumping around the `rules_nixpkgs` upgrade and not observe the issue, but I can also observe it sometimes after minors changes in my sources.

**Expected behavior**

I don't want unpredictable failures. Actually that's not a dramatic issue to work (we just need to run bazel again), but it makes continuous integration difficult because it may randomly fail.

**Environment**

- Linux, happened on different flavors of nixos or ubuntu
- Bazel 0.22 from nixpkgs
 - Version of the rules: 67a80de8648b2b40a3b7f5b4b8b7f2ad95c1a08c

**Additional context**

I'm opening the issue for tracking. If nobody have the same issue, I'll conclude as an issue specific from our setup.

**Comment by aherrmann** [comment]
@guibou Just a hunch: [This code](https://github.com/tweag/rules_nixpkgs/commit/67a80de8648b2b40a3b7f5b4b8b7f2ad95c1a08c#diff-c63e8f1a3d7833e781c59c7391324cd6R180) seems to assume that every line of stderr output of nix-build has at least two words on it separated by space. Maybe that's occasionally not the case and causes these random failures.

**Comment by guibou** [comment]
@aherrmann Good catch. I'll push a fix for this line and we'll see if it helps fixing the issue.

**Comment by guibou** [comment]
@aherrmann well done. It was indeed the problem and understanding it helped to make a reproduction code and validate it.
