### ISSUE TITLE
Remove `nixpkgs_git_repository`, it clashes with nix_file_deps heuristics

### ISSUE THREAD

**Issue by Profpatsch** [tweag/rules_nixpkgs#81]
A [minimal `WORKSPACE` setup of `rules_haskell`](https://github.com/tweag/rules_haskell/issues/855#issuecomment-488819184) that uses `nixpkgs_git_repository` [fails on current master](https://github.com/tweag/rules_nixpkgs/pull/76#issuecomment-488818048) because `nixpkgs_git_repository` checks out nixpkgs into a bazel repository, which makes the heuristic require to manually specify every single file from the checked out nixpkgs. See [this discission](https://github.com/tweag/rules_nixpkgs/pull/76#issuecomment-488818048).

@guibou [says](https://github.com/tweag/rules_nixpkgs/pull/76#issuecomment-490043538):

> You can imagine a even more minimal setup such as:
> ```
> haskell_register_ghc_nixpkgs(
>    version = "8.4.3",
>    repositories = { "nixpkgs": ":nixpkgs.nix" }
>)
>```
>
> Where nixpkgs.nix contains the relevant fetchTarball call. This solution does not use nixpkgs_git_repository and is more reproducible. Actually, I just realized that nixpkgs_git_repository does not forces the usage of the sha256 argument and hence is not reproducible.

So the best plan of action we figured out is to ask the user to use the nix-based `fetchTarball` approach and remove `nixpkgs_git_repository`.

cc @regnat @mboes

**Comment by samrose** [comment]
@Profpatsch is this still considered an issue for `rules_nixpkgs` ? 

I took note that this was posted on 2019 (although I do see it is labelled "priority 1").

If someone were to submit a pull request on this: are you simply looking to remove `nixpkgs_git_repository` plus update the examples? It appears that `nix_local_repository` already covers the minimal setup example you have in the original issue.

**Comment by aherrmann** [comment]
@samrose Thanks for the ping! This has been fixed in the meantime, the repository now also includes [working examples](https://github.com/tweag/rules_nixpkgs/blob/74c40cf36e9a79bafc59e745c3d1e49ec3098b23/examples/toolchains/cc/WORKSPACE#L27) that use `nixpkgs_git_repository`.

**Comment by samrose** [comment]
@aherrmann thanks! If someone wants to contribute to this repo, what do you think are some good inroads toward PR if any?

**Comment by aherrmann** [comment]
@samrose this one may be a good starting point: https://github.com/tweag/rules_nixpkgs/issues/143
