### ISSUE TITLE
Verbosity of nixpkgs_package

### ISSUE THREAD

**Issue by guibou** [tweag/rules_nixpkgs#82]
Current `nixpkgs_package` is quiet during package installation. It can be mute as such for a really long time if the nix process is long, giving no user feedback. In case of error, it shows a highly verbose nix output which is totally unusable for the user.

This changes are due to #77, in which  removed the verbosity of `nixpkgs_package`. This was mostly due to #76 which introduced an heuristic for better reproducibility, but this heuristic is using the highly verbose output of `nixpkgs_package` that user do not want to see.

I propose to implement two changes:

- The underlying `nix-build` process will be run twice. Once with nix normal verbosity and the second time with the highest verbosity.
- A `quiet` option will be added to `nixpkgs_package` (and associated rules). It default to `True`, but when switched to `False` it will display the progress of the `nix-build` command, using the normal output.

The heuristic will be computed using the output of the second run. This way, if first run fails, or `quiet` is set to `False`, user will see an informative output. The second run should never fail.

This will introduce a bit of overhead because `nix-build` will be called twice.

# Alternative solutions

- split the build between `nix-instanciate` and `nix-build` and only run the heuristic (hence verbose output) on the `nix-instanciate` call, and setting the `quiet` flag on the `nix-build` call. This will be an improvement in case of error during the `nix-build` phase, however if any error occur during the `nix-instanciate` phase, user will still face a long and verbose output.

Should I implement that?

**Comment by guibou** [comment]
@mboes

**Comment by guibou** [comment]
@Profpatsch @aherrmann

**Comment by mboes** [comment]
I think we're spending too many brain cycles that could be more productively spent elsewhere. I'm not a fan of #76, and not a fan of any of the proposed solutions in this ticket. If we'd just ignore the problem, everything would stay simple. #77 started from a false premise: that Bazel rules are expected to be quiet. I have seen that being said (including by myself), though not substantiated by Bazel documentation, and what applies to build rules need not apply to workspace rules.

Workspace rules are not sandboxed. It would be better if they were (we should file an upstream ticket if there isn't one already), but that's the current state of play. If reimplementing our own mini sandboxing is having knock-on effects, then let's kill it and let the user deal with incorrect workspace rules - they'll be having many others than ours to deal with anyways.

**Comment by aherrmann** [comment]
In defense of #76: It has been very useful for us in tracking down hermeticity issues. We're using Nix provided GHC and cc-toolchain on Linux and MacOS. If a corresponding Nix file is not listed in `nix_file_deps`, then this can lead to very subtle and confusing errors. E.g. if one developer updates GHC or the cc-toolchain, then another developer might start seeing errors due to missing Nix store references or other errors due to version mismatch. `bazel clean --expunge` will typically fix that. Of course the correct solution is to have an exhaustive `nix_file_deps` attribute.

> #77 started from a false premise: that Bazel rules are expected to be quiet.

One use case for quiet Bazel rules is automated tooling that consumes the output of `bazel query`. If workspace rules print additional output to stdout, then such tools might misinterpret such additional output as query results. A workaround is to first run `bazel fetch --keep_going //...`. Though, I suspect this might miss cases where the query covers external workspaces that are not referenced within `//...`.

**Comment by guibou** [comment]
@mboes for the upstream report about sandboxing of external repository in bazel. I opened it 3 months ago: https://github.com/bazelbuild/bazel/issues/7764

I don't like the current status of #76 either, but it helped a lot here to avoid ugly, really ugly bugs. Due to caching, we had totally unhermetic builds running in production here. I had never tried to build a real sandbox myself however. It may be solved quickly, or take time, I have no idea and that's not on the priority list.

However, #76 introduced a lot of verbosity in the output, that's why I created #77, but that's not the only reason. As @aherrmann discussed, I had users who were using the output of `bazel query` in scripts and it was breaking their scripts.

Bazel could provide more way to report progress during repository building, see my comment here: https://github.com/bazelbuild/bazel/issues/1289#issuecomment-486975299 but that's not the case for now.

I had no more than 5 minutes ago a client who was curious about why `bazel build` was blocked since more than one hour on `fetch @ghc-toolchain`. He was not aware that this "fetching" was in fact building ghc itself and more than 300 haskell packages.

**Comment by mboes** [comment]
Nix is so slow that doubling the cost of each `nixpkgs_package` is not worth it I think.

I'm not sure why #76 was implemented the way it was. Here's another solution: copy the declared nix files in some empty folder (evaluation will fail if a file is missing in the folder or any subdirectories). That should require far less code. Let me know if you already tried that.

**Comment by guibou** [comment]
@mboes Your solution is smart but not enough if nix files depends on an absolute path.

**Comment by mboes** [comment]
They never should. Do you have an example?

Absolute paths kill even sandboxing.

**Comment by guibou** [comment]
@mboes global nixpkgs configuration. (in `~/.config/nixpkgs/...`).

**Comment by mboes** [comment]
I disagree that this is reasonable. If you need to pass flag to nix, use `nixopts`. A global configuration file makes the build entirely non-hermetic.

**Comment by guibou** [comment]
@mboes yes, that's the point. We want to be able to detect that user are using file in `~/.config/nixpkgs/...` and tell them that their build are not reproducible. The current implementation detect that and complains.
Your proposal won't.

**Comment by mboes** [comment]
I do not want to be spending 70+ lines just to detect absolute paths in Nix files (like #76 added). We then have to spend multiple people's brain cycles to figure out a solution to this issue. It would all go away if you did the simple thing that gave you 80% of what you're looking for.

**Comment by guibou** [comment]
Ok fine. I'm closing this issue and opening two new issues;

- Rework #76 and implement your simpler solution
- A discussion on how to increase the verbosity of `nixpkgs_package`. (I.e. this issue, but in the context of #76 rework)

**Comment by mboes** [comment]
Note that with this simpler solution, verbosity can stay exactly as before. I don't think controlling verbosity in an attribute is the right approach, nor do I believe it necessary to control this.

**Comment by guibou** [comment]
I'll let you continue this discussion in the relevant issue.

**Comment by mboes** [comment]
Point is - the second issue is unneeded. Let's fix #84 and then regroup.
