### ISSUE TITLE
Consider exposing all files in a filegroup

### ISSUE THREAD

**Issue by Fuuzetsu** [tweag/rules_nixpkgs#9]
Currently we only expose `.so` files from `lib` and things from `bin`: this is quite restrictive: we can't use header files or use binaries that don't live directly in `bin` &c.

Is there any good reason to not have an `out` file group that user can reach for?

Related question: can use filter filegroups? That'd be very useful.

**Comment by mboes** [comment]
What are filter filegroups?

**Comment by Fuuzetsu** [comment]
I mean can you take a filegroup as a user and filter it, only passing some subset of files to rules &c.
